### ISSUE TITLE
请问怎么下载自动构建包

### ISSUE THREAD

**Issue by windy1021** [kengwang/HyPlayer#5]

**Comment by kengwang** [comment]
由于目前处于开发阶段,暂无人工编译包. 自动编译包可以去 Azure 中下载
由于上一次提交为编译成功,你可以下载之前的包: https://dev.azure.com/kengwang/c353f3d8-cb71-45a4-921d-ad8e6f898505/_apis/build/builds/1098/artifacts?artifactName=drop&api-version=6.0&%24format=zip

**Comment by kengwang** [comment]
https://ws28.cn/f/4srx60s9i7i
